name: nps_social
description: A Flutter project from NPS Team.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Handle packages
  get: ^4.6.5                           # https://pub.dev/packages/get
  shared_preferences: ^2.0.15
  http: ^0.13.5
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  permission_handler: ^10.1.0
  url_launcher: ^6.1.6                  # https://pub.dev/packages/url_launcher
  dio_http_cache: ^0.3.0 
  image_picker: ^0.8.6                  # https://pub.dev/packages/image_picker
  path_provider: ^2.0.11
  cloudinary_public: ^0.13.0
  intl: ^0.17.0
  socket_io_client: ^2.0.0
  geolocator: ^9.0.2
  peerdart: ^0.3.2
  share_plus: ^6.3.0

  # UI packages
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.14
  # flutter_launcher_icons: ^0.11.0
  animated_size_and_fade: ^3.0.0
  ionicons: ^0.1.2                        # https://ionicons.ez-connect.net/#/
  font_awesome_flutter: ^10.2.1           # https://pub.dev/packages/font_awesome_flutter
  flutter_local_notifications: ^12.0.2    # https://pub.dev/packages/flutter_local_notifications
  cached_network_image: ^3.2.2
  # image_collapse: ^1.0.0                  # https://pub.dev/packages/image_collapse
  image_collage: ^0.0.4                   # https://pub.dev/packages/image_collage
  flutter_spinkit: ^5.1.0
  image_viewer: ^1.5.0
  unicons: ^2.1.0
  carousel_slider: ^4.1.1
  timeago: ^3.3.0
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  syncfusion_flutter_maps: ^20.3.59
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - .env

    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # https://flutter.dev/custom-fonts/#from-packages
