name: npssolutions_mobile
description: A Flutter project from NPS Team.


version: 1.0.0+1


environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ^3.3.10


dependencies:
  flutter:
    sdk: flutter

  # Handle packages
  provider: ^6.0.5
  get: ^4.6.5
  shared_preferences: ^2.0.15
  json_annotation: ^4.8.0
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.6+3
  intl: ^0.18.0
  package_info_plus: ^3.0.3

  # UI packages
  cupertino_icons: ^1.0.2
  rive: ^0.10.0
  flutter_svg: ^2.0.0+1
  animated_toggle_switch: ^0.6.1
  font_awesome_flutter: ^10.3.0
  hexcolor: ^3.0.1
  google_fonts: ^4.0.3
  ionicons: ^0.2.2
  emerge_alert_dialog: ^0.0.3
  sidebarx: ^0.15.0
  drop_shadow: ^0.1.0
  card_loading: ^0.3.0
  auto_animated: ^3.1.0
  flutter_speed_dial: ^6.2.0
  rounded_loading_button: ^2.1.0
  multi_select_flutter: ^4.1.3
  flutter_slidable: ^2.0.0
  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.5
  simple_loading_dialog: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - .env

    - assets/Backgrounds/
    - assets/RiveAssets/
    - assets/icons/
    - assets/icons/png/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700